### ISSUE TITLE
PST50W i Homey

### ISSUE THREAD

**Issue by Oz19851985** [PetterRuud/com.scinan.api#14]
Hei, ønsker å laste inn min PST50W til Profag i Homey, men får en feilmelding når jeg prøver å registrere denne i Scinan appen.
Jeg får feilmelding: typerror: result.forEach is not a function. 
Jeg bruker innlogging som jeg har til Profag PST50W.

Setter pris på hjelp!
Åsmund

**Comment by late4marshmellow** [comment]
Jobber med å finne en løsning på dette men har i utgangspunktet ingen javascript kunnskaper.
Håper @PetterRuud kan ta en titt på mine oppdagelser i min fork for å gjøre en oppdatering eventuelt peke meg i rett retning :) .

finner jeg ut av det vil jeg etterhvert laste min versjon opp som en app i homey store om ingenting skjer med den orginale her :)

**Comment by PetterRuud** [comment]
> Jobber med å finne en løsning på dette men har i utgangspunktet ingen javascript kunnskaper. Håper @PetterRuud kan ta en titt på mine oppdagelser i min fork for å gjøre en oppdatering eventuelt peke meg i rett retning :) .
> 
> finner jeg ut av det vil jeg etterhvert laste min versjon opp som en app i homey store om ingenting skjer med den orginale her :)

Har flyttet og derfor ikke noe utstyr å få testet appen lenger. Ta gjerne å lag en pull request med fiks.

**Comment by PetterRuud** [comment]
Legg Gjerne inn en PR for feil, så skal jeg se. Ser det bra ut så har jeg ikke noe i mot å gjøre deg til maintainer
