### ISSUE TITLE
Hente token

### ISSUE THREAD

**Issue by late4marshmellow** [PetterRuud/com.scinan.api#16]
Hei igjen! Takk for at du tittet innom og oppdaterte. Om det ikke er for mye å be om... :)

Jeg sliter med å løse det at POST av URL ikke lengere logger rett inn og så scriptet kan hente ut token. 

Forsøkt å leke meg litt med user-agent via postman men treffer ikke bingo. 

Lurer litt på hvilken user-agent smart-e appen i iOS fra saswell bruker. Denne er versjon 3.2.5
Tenkte det kunne holde å oppdatere dette nummeret men resulterer likevel i ett innloggingsbilde (i postman)
Har også forsøkt å endre alt til Smart-E/3.2.5 (iPhone13,4; iOS 16_0_3; Scale/3.00) men, fortsatt innlogings bilde.

Hvordan fant du ut av user-agent strengen første gangen? URL i det heletatt, hadde du kontakt med scinan?
 
hvis det ikke lengere er mulig å komme rett til token via POST URL

leder det meg videre til om en skulle endret koden til å dyttet userId og passwd inn i de rette feltene i det nye bildet for så submitte dette via en GET forespørsel? 

Derifra kan koden fortsette som før med å indeksere og plukke ut token. 

Men kan vel ikke stemme at de har fjernet tilgang direkte til token via URL? 

Kan godt lage egen konto til termostat på gjesterom som du kan prøve deg på om du har lyst og tid :D

**Comment by PetterRuud** [comment]
Kjør igjennom en proxy, les mer her https://blog.postman.com/using-postman-proxy-to-capture-and-inspect-api-calls-from-ios-or-android-devices/. Da ser du hele flyten mellom appen og scinan apiet og kan sjekke kallene og responsene.

Finnes andre verktøy enn Postman for dette, men siden du nevnte det det, så la jeg ved den lenken. Bruker SoapUI selv for dette.

**Comment by late4marshmellow** [comment]
takk :) føler jeg fikk løst ganske mye nå. 
men ikke helt sikker på hvordan jeg skal få det ned på scriptet.
javascript er helt ferskt for meg :D 

user-agent hos meg er Smart-E/3.2.5 (iPhone; iOS 16.0.2; Scale/3.00)
etter å ha lekt meg med postman virker det uansett om som user-agent er mindre viktig. 

url som skal benyttes er kun https://api.scinan.com/oauth2/authorize

alt fra Params kan flyttes over i enten form-data eller x-www-form-urlencoded som header. 

har også forsøkt å kjøre POST uten noen headers og token kommer frem i preview uansett.  

men får ikke det helt til når jeg forsøker å sette sammen script i homey.
føler jeg er inne på noe,..

`'use strict';
const Homey = require('homey');
const fetch = require('node-fetch');
const { getTimestamp, getStatus } = require('./Utils');
const { AUTHORIZATION_URL, LIST_URL, USER_AGENT, CLIENT_ID, REDIRECT_URI } = require('./Constants');

class ScinanDriver extends Homey.Driver {
  onInit() {}

  async getToken(username, password) {
    this.homey.settings.set('username', username);
    this.homey.settings.set('password', password);

    try {
		
var details = {
'client_id': CLIENT_ID,
'passwd': password,
'redirect_uri': REDIRECT_URI,
'response_type': 'token',
'userId:': username

};

var formBody = [];
for (var property in details) {
  var encodedKey = encodeURIComponent(property);
  var encodedValue = encodeURIComponent(details[property]);
  formBody.push(encodedKey + "=" + encodedValue);
}
formBody = formBody.join("&");


					
      const response = await fetch(`https://api.scinan.com/oauth2/authorize`,
        {
          body: formBody,
		  method: 'POST',
		    headers: {'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'},
      );

      if (response.ok) {
        const html = await response.text();
        const start = html.indexOf('token:');
        const end = html.indexOf('\n', start);
        const token = html.substring(start + 6, end);

		
		this.homey.settings.set('token', token);
        return token;
      }
      this.log('no_token');
      throw new Error('no_token');
    } catch (error) {
      this.log(error);
      throw new Error(error);
    }
  }

  async getDevices() {
    const token = this.homey.settings.get('token');
    const timestamp = getTimestamp(new Date());

    try {
      const response = await fetch(`${LIST_URL}?format=json&timestamp=${timestamp}&token=${token}`, {
        method: 'GET',
        headers: {
          'User-Agent': USER_AGENT,
        },
      });

      if (response.ok) {
        const result = await response.json();
        let devices = [];
        Array.prototype.forEach.call(result, device => {
          this.log(device);
          const status = getStatus(device.status);
          devices.push({
            name: device.title,
            data: {
              name: device.title,
              id: device.id,
              onoff: status.onoff,
              online: device.online,
              away: status.away,
              measure_temperature: status.measure_temperature,
              target_temperature: status.target_temperature,
              mode: status.mode,
              last_updated: status.time,
            },
          });
        });
        return devices;
      }
    } catch (error) {
      this.log(error);
      throw new Error(error);
    }
  }

  async onPair(session) {
    session.setHandler('login', async data => {
      if (data.username === '' || data.password === '') return null;
      await this.getToken(data.username, data.password);
      return true;
    });

    session.setHandler('list_devices', async data => {
      return await this.getDevices();
    });
  }
}

module.exports = ScinanDriver;
`

**Comment by late4marshmellow** [comment]
tror jeg endelig har løst det nå, etter å ha testet litt inne i homey script. 
skal teste på min homey pro ikveld, sender pull request hvis det fungerer :)

**Comment by late4marshmellow** [comment]
Hei Petter!

Jeg har nå skrevet en god del ny kode for å få appen til å virke med ny versjon saswell api. 
Men siden du ikke oppdaterer appen lengere og det er såpass mye nytt tenker jeg at denne heller bør lastes opp i Homey Store som en egen app. samtidig ønsker jeg også å beholde noe av din kode i forhold til opprinnelig scinan v1 dersom noen fortsatt bruker dette... hva tenker du om det?

Kontakt meg gjerne direkte via Homey Community om du heller ønsker å ta dette privat. jeg har samme kallenavn der..

**Comment by PetterRuud** [comment]
Har sent deg en invite som collabator nå. 
Hva er Homey developer user Id din, så kan jeg flytte appen til deg.

**Comment by late4marshmellow** [comment]
> Har sent deg en invite som collabator nå. Hva er Homey developer user Id din, så kan jeg flytte appen til deg.

61d450b74a93030bcc33ff16
