### ISSUE TITLE
App crashing on startup

### ISSUE THREAD

**Issue by Bacalhauabada** [PetterRuud/com.scinan.api#3]
App crashes on startup every time. Have tried restarting Homey and restarting the app x amount of times without luck.
Sorry if this is such an obvious error that it shouldn't even be reported since I'm very new tom Homey and github. (I was just so excited to find and app that could control my Profag PST50)

**Comment by PetterRuud** [comment]
I'll fix, its because i havent added the npm modules folder to the repo.

**Comment by PetterRuud** [comment]
1.0.2 submitted
