### ISSUE TITLE
Support for T19WHB-7-DF

### ISSUE THREAD

**Issue by ronald2404** [PetterRuud/com.scinan.api#4]
Hello I am thinking of buying 
T19WHB-7-DF

https://nl.aliexpress.com/item/4000183739338.html?spm=a2g0o.detail.1000023.1.6bf479c8yhS6cS

Is it easy for you to support these device? 

I am searching for cheap Room thermostat to control by my homey. So I can control mt lyrics T6 and eurotronic spirit valves.

Regards

Ronald

**Comment by ronald2404** [comment]
also your thermostat looks like this one but has a different model nr
https://nl.aliexpress.com/item/4000114484613.html?spm=a2g0o.productlist.0.0.96e34e0eLZigOk&algo_pvid=3688bc4d-a3ea-4c6e-a038-5c5922139b40&algo_expid=3688bc4d-a3ea-4c6e-a038-5c5922139b40-13&btsid=ffaf2274-fc48-4cdd-80d7-229200d0e1f9&ws_ab_test=searchweb0_0,searchweb201602_3,searchweb201603_52

**Comment by PetterRuud** [comment]
If it uses the scinan API, its very easy add support for it. I'll take a quick look and see.

**Comment by PetterRuud** [comment]
I have checked and I see that T19WHB-7-DF uses the Tuya app. So I'm 99% sure it uses another API than scinan. So I cant support it.

**Comment by ronald2404** [comment]
Hi Peter, Thanks for checking.  that is unfortunate, but nothing we can do a bout it. Ill see What your supported devices cost and if it fits my need.

**Comment by PetterRuud** [comment]
There are probably more devies that are supported (If they use scinan api). Those I have listed is is the two I have at home
