### ISSUE TITLE
Support for Veria Clickkit 55 thermostat

### ISSUE THREAD

**Issue by kenmyh** [PetterRuud/com.scinan.api#6]
Is Veria Clickkit 55 thermostat the same as Pergo, and the same api?

**Comment by PetterRuud** [comment]
It probably is. Is there an iOS/Android app for it? Makes it easy for me to test as all the apps use the same credentials.

**Comment by kenmyh** [comment]
I haven't found any. It all looks the same as pergo, that is all I know. The data I've found is this https://www.veriafloorheating.com/no/produkter/veria-termostater/veria-wireless-clickkit-55-100/?doc=documentation

**Comment by PetterRuud** [comment]
It does not seem to use the API at all. Looks like it only communication is between the box and the controller. So no internet communication like the ones using scinan. Thay maybe a good thing that no can hijack your floor heating nor China getting knowing what temperature you like ;)
