### ISSUE TITLE
Support for nye Quickheat trådløs termostat

### ISSUE THREAD

**Issue by kenmyh** [PetterRuud/com.scinan.api#7]
Jeg regner med at det går fint med norsk. Vet du om det er samme termostat på varmefolien til pergo som varmemattene? Ser at det ikke er så mange som fører varmemattene lenger. Tenker da på denne https://www.obsbygg.no/gulv-og-tilbehor/gulvtilbehor/2082437?v=ObsBygg-5400818895792

Kan den styres fra denne appen til Homey?

Kenneth

**Comment by PetterRuud** [comment]
Den skal ikke være noe problem å å få lagt til i Homey. Kan legge den til appen i løpet av uken.

**Comment by PetterRuud** [comment]
Da kan du prøve å legge den til. Pergo Trådløs
