### ISSUE TITLE
Could not find that Driver

### ISSUE THREAD

**Issue by Finnsen** [PetterRuud/com.scinan.api#8]
Får feilmeldingen «Could not find that Driver» når jeg prøver å installere nye Pergo Quickheat termostat.

Homey Pro, siste firmware.

Might it be missing dependencies?

**Comment by Finnsen** [comment]
Når jeg kjører appen fra CLI får jeg denne feilmeldingen:

```
─────────────── Logging stdout & stderr ───────────────
Unable to initialize app TypeError: Cannot read property 'manifest' of undefined
    at ScinanApp.onInit (/app.js:5:61)
    at SDK._initApp (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/SDK.js:284:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async SDK.createClient (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/SDK.js:172:5)

--- INFO: com.scinan.api has been killed ---

```

**Comment by Finnsen** [comment]
Det ser ut som om du har endret SDK til versjon 3 uten å oppdatere koden. Når jeg endret app.json til sdk2 så fungerer det fint.

**Comment by PetterRuud** [comment]
Hvilken versjon kjører du på Homey? 4 eller 5?

**Comment by Finnsen** [comment]
Jeg kjører 5.

Mvh
Ragnar Anfinsen

**Comment by PetterRuud** [comment]
https://homey.app/a/com.scinan.api/test/

Test denne, har fikset feilmeldingene.

**Comment by Finnsen** [comment]
Strålende, den fungerer fint. Takk skal du ha. Har lært mye om Homey koding ved å feilsøke denne. :)

**Comment by Finnsen** [comment]
Var litt rask der. Når jeg prøver å endre kvadratmeter så får jeg feilmeldingen 'Cannot read property 'interval' of undefined'. Regner med det er SDK2 > SDK3 issue det også?

**Comment by PetterRuud** [comment]
Skal se på det. Har flyttet og har gått fra varmefolie til varmekabler. Så litt vanskligere å teste.

**Comment by Finnsen** [comment]
Jeg kan godt være med å teste og evnt. bidra litt. Er snakker ikke JS nativt, men har nok kunnskap til å feilsøke og fikse bugs.

**Comment by PetterRuud** [comment]
Bare å legge inn PR
